server:
  port: 8888
  
spring:
  application:
    name: config-service
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
  cloud:
    config:
      server:
        git:
          uri: https://github.com/sohot8653/st-framework.git
          username: sohot8653
          password: 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
          default-label: master
          search-paths:
          - outer/config-service/config-file
management:
  endpoints:
    web:
      exposure:
        include: health, busrefresh